name: Release ml-wrappers to PyPI

# trigger manually only ("collaborator" or more permissions required)
on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: "Test or Prod PyPI?"
        required: true
        default: "Test"

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - name: fail if Test nor Prod
        if: ${{ ! (github.event.inputs.releaseType == 'Test' || github.event.inputs.releaseType == 'Prod') }}
        run: |
          echo "Only Test or Prod can be used."
          exit 1

      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.9

      - if: ${{ matrix.operatingSystem != 'macos-latest' }}
        name: Install pytorch on non-MacOS
        shell: bash -l {0}
        run: |
          conda install --yes --quiet "pytorch<2.0.0" torchvision captum cpuonly -c pytorch -c conda-forge --strict-channel-priority

      - if: ${{ matrix.operatingSystem == 'macos-latest' }}
        name: Install Anaconda packages on MacOS, which should not include cpuonly according to official docs
        shell: bash -l {0}
        run: |
          conda install --yes --quiet pytorch torchvision captum -c pytorch

      - name: update and upgrade pip, setuptools, wheel, and twine
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel twine

      - name: Install backwards-compatible tf-keras for transformers
        shell: bash -l {0}
        run: |
          pip install tf-keras

      - name: Install dev dependencies
        shell: bash -l {0}
        run: |
          pip install -r requirements-dev.txt
    
      - name: Install test dependencies
        shell: bash -l {0}
        run: |
          pip install -r requirements-test.txt

      - name: pip freeze
        shell: bash -l {0}
        run: pip freeze

      - name: build wheel for ml-wrappers
        shell: bash -l {0}
        run: python setup.py sdist bdist_wheel
        working-directory: python

      # run tests before publishing to PyPI
      - name: install ml-wrappers wheel locally
        shell: bash -l {0}
        run: find ./dist/ -name '*.whl' -exec pip install {} \;
        working-directory: python

      - name: run ml-wrappers tests
        shell: bash -l {0}
        run: pytest ./tests/main

      - name: Upload a ml-wrappers build result
        uses: actions/upload-artifact@v2
        with:
          name: ml_wrappers
          path: python/dist/

      # publish to PyPI
      - name: Publish ml-wrappers package to Test PyPI
        if: ${{ github.event.inputs.releaseType == 'Test' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN_ML_WRAPPERS }}
          repository_url: https://test.pypi.org/legacy/
          packages_dir: python/dist/
      - name: Publish ml-wrappers package to PyPI
        if: ${{ github.event.inputs.releaseType == 'Prod' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN_ML_WRAPPERS }}
          packages_dir: python/dist/
